#!/bin/bash
set -e

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.' >&2
  exit 1
fi

# patch by default.
# Use `./release minor` or `./release major`.
VERSION_TYPE=${1-patch}

# git fetch;
# git checkout release --;
# git rebase main;
npm version $VERSION_TYPE;
VERSION=$(cat package.json | jq -r '.version');
for PACKAGE in common node web; do
  FILE=packages/$PACKAGE/package.json
  jq --arg new_version "$VERSION" '.version = $new_version' $FILE > $FILE.tmp && mv $FILE.tmp $FILE
done
# git push -f;
# git checkout main;
# git rebase origin/release;
# git push --tags --no-verify;
# git push --no-verify;
# echo https://github.com/Railgun-Community/waku-relayer-client/actions;
