#!/bin/bash
set -e

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.' >&2
  exit 1
fi

CURRENT_BRANCH=$(git branch --show-current)

# prepatch by default, script is ran like ./release-dev <branch-name>
VERSION_TYPE=prepatch

# Sync
COMMIT_HASH=$(git rev-parse --short HEAD)

git fetch;
git pull; # In case there are new commits from desired branch
git checkout dev --;
git rebase $CURRENT_BRANCH;

# Update version in root package.json
npm version $VERSION_TYPE --preid=$COMMIT_HASH;

# Propagate version to packages
VERSION=$(cat package.json | jq -r '.version');
for PACKAGE in common node web; do
  FILE=packages/$PACKAGE/package.json
  jq --arg new_version "$VERSION" '.version = $new_version' $FILE > $FILE.tmp && mv $FILE.tmp $FILE
done

# Amend the version commit
git add .
git commit --amend --no-edit;
git tag -d v$VERSION;
git tag v$VERSION;

# Push
git push -f;
git checkout $1;
git rebase origin/dev;
git push --tags --no-verify;
git push --no-verify;
echo "The release will be made from https://github.com/Railgun-Community/waku-broadcaster-client/actions";
